### PR TITLE
Readme formatting

### PR DESCRIPTION
**Pull request by boltronics**
Addresses issue https://github.com/santouras/foosball/issues/15.

### CODE REVIEW

**Comment by santouras** [comment]
awesome :+1:

**Comment by AdamRobertsNZ** [comment]
Nice one @boltronics - one other minor thing I wanted to do was to change "-" to "--" in the last two intro quotes. Worth incorporating that into this PR?

**Comment by santouras** [comment]
@AdamRobertsNZ I think so. Would you be able to get this up to date with `master` as well via rebasing?

**Comment by boltronics** [comment]
Done. Results are viewable here: https://github.com/boltronics/foosball/tree/readme_formatting

**Pull request merged**
